//! Ray queries: the inline ray-tracing surface WGSL exposes.
//!
//! Naga supplies the two struct types involved — `RayDesc` for what to trace
//! and `RayIntersection` for what was found — so they are generated on demand
//! rather than declared here, and their field names come from Naga.
//!
//! A query is a variable the operations act on, and as with the atomics it is
//! passed directly rather than by reference: nothing else could be meant.

use naga::{Block, Expression, Function, Handle, RayQueryFunction, Scalar, Span, Statement, Type};
use syn::Expr;

use super::emit::emit;
use super::env::Env;
use super::{Context, Typed};
use crate::Error;

/// `acceleration_structure` and `ray_query`, which take no type arguments.
pub(super) fn parse_ray_type(ctx: &mut Context, name: &str) -> Option<Handle<Type>> {
    let inner = match name {
        "acceleration_structure" => naga::TypeInner::AccelerationStructure {
            vertex_return: false,
        },
        "ray_query" => naga::TypeInner::RayQuery {
            vertex_return: false,
        },
        _ => return None,
    };
    Some(ctx.intern_handle_type(inner))
}

/// `RayDesc` and `RayIntersection`, generated by Naga the first time they are
/// named so that their layout matches what the backends expect.
pub(super) fn special_struct(ctx: &mut Context, name: &str) -> Option<Handle<Type>> {
    match name {
        "RayDesc" => Some(ctx.module.generate_ray_desc_type()),
        "RayIntersection" => Some(ctx.module.generate_ray_intersection_type()),
        _ => None,
    }
}

/// The predeclared ray flags and intersection kinds, which WGSL provides as
/// bare names rather than as constants anyone declares.
pub(super) fn predeclared_const(name: &str) -> Option<u32> {
    use naga::RayFlag;
    let value = match name {
        "RAY_FLAG_NONE" => RayFlag::empty().bits(),
        "RAY_FLAG_FORCE_OPAQUE" => RayFlag::FORCE_OPAQUE.bits(),
        "RAY_FLAG_FORCE_NO_OPAQUE" => RayFlag::FORCE_NO_OPAQUE.bits(),
        "RAY_FLAG_TERMINATE_ON_FIRST_HIT" => RayFlag::TERMINATE_ON_FIRST_HIT.bits(),
        "RAY_FLAG_SKIP_CLOSEST_HIT_SHADER" => RayFlag::SKIP_CLOSEST_HIT_SHADER.bits(),
        "RAY_FLAG_CULL_BACK_FACING" => RayFlag::CULL_BACK_FACING.bits(),
        "RAY_FLAG_CULL_FRONT_FACING" => RayFlag::CULL_FRONT_FACING.bits(),
        "RAY_FLAG_CULL_OPAQUE" => RayFlag::CULL_OPAQUE.bits(),
        "RAY_FLAG_CULL_NO_OPAQUE" => RayFlag::CULL_NO_OPAQUE.bits(),
        "RAY_FLAG_SKIP_TRIANGLES" => RayFlag::SKIP_TRIANGLES.bits(),
        "RAY_FLAG_SKIP_AABBS" => RayFlag::SKIP_AABBS.bits(),
        "RAY_QUERY_INTERSECTION_NONE" => naga::RayQueryIntersection::None as u32,
        "RAY_QUERY_INTERSECTION_TRIANGLE" => naga::RayQueryIntersection::Triangle as u32,
        "RAY_QUERY_INTERSECTION_GENERATED" => naga::RayQueryIntersection::Generated as u32,
        "RAY_QUERY_INTERSECTION_AABB" => naga::RayQueryIntersection::Aabb as u32,
        _ => return None,
    };
    Some(value)
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum RayOp {
    Initialize,
    Proceed,
    GenerateIntersection,
    ConfirmIntersection,
    Terminate,
    GetCommitted,
    GetCandidate,
}

impl RayOp {
    /// Which of these hand a value back: `rayQueryProceed` and the two
    /// intersection getters. The rest only act on the query.
    pub(super) fn is_statement(self) -> bool {
        !matches!(
            self,
            RayOp::Proceed | RayOp::GetCommitted | RayOp::GetCandidate
        )
    }
}

pub(super) fn ray_builtin(name: &str) -> Option<RayOp> {
    Some(match name {
        "rayQueryInitialize" | "ray_query_initialize" => RayOp::Initialize,
        "rayQueryProceed" | "ray_query_proceed" => RayOp::Proceed,
        "rayQueryGenerateIntersection" | "ray_query_generate_intersection" => {
            RayOp::GenerateIntersection
        }
        "rayQueryConfirmIntersection" | "ray_query_confirm_intersection" => {
            RayOp::ConfirmIntersection
        }
        "rayQueryTerminate" | "ray_query_terminate" => RayOp::Terminate,
        "rayQueryGetCommittedIntersection" | "ray_query_get_committed_intersection" => {
            RayOp::GetCommitted
        }
        "rayQueryGetCandidateIntersection" | "ray_query_get_candidate_intersection" => {
            RayOp::GetCandidate
        }
        _ => return None,
    })
}

pub(super) fn lower_ray_call(
    ctx: &mut Context,
    function: &mut Function,
    body: &mut Block,
    call: &syn::ExprCall,
    env: &mut Env,
    name: &str,
    op: RayOp,
) -> Result<Typed, Error> {
    let args: Vec<&Expr> = call.args.iter().collect();
    let want = match op {
        RayOp::Initialize => 3,
        RayOp::GenerateIntersection => 2,
        _ => 1,
    };
    if args.len() != want {
        return Err(Error::WrongArgCount(name.into()));
    }

    // The query is storage the operation mutates, so it comes through the place
    // walk rather than as a loaded value.
    let place = super::place::lower_place(ctx, function, body, args[0], env)?
        .ok_or_else(|| Error::NotAPlace(name.into()))?;
    if !matches!(
        ctx.module.types[place.ty].inner,
        naga::TypeInner::RayQuery { .. }
    ) {
        return Err(Error::NotARayQuery(name.into()));
    }
    let query = place.pointer;

    let fun = match op {
        RayOp::Initialize => {
            let (acceleration_structure, acc_ty) =
                super::expr::lower_expr(ctx, function, body, args[1], env)?;
            if !matches!(
                ctx.module.types[acc_ty].inner,
                naga::TypeInner::AccelerationStructure { .. }
            ) {
                return Err(Error::NotAnAccelerationStructure(name.into()));
            }
            let (descriptor, _) = super::expr::lower_expr(ctx, function, body, args[2], env)?;
            RayQueryFunction::Initialize {
                acceleration_structure,
                descriptor,
            }
        }
        RayOp::GenerateIntersection => {
            let (hit_t, _) = super::expr::lower_expr(ctx, function, body, args[1], env)?;
            RayQueryFunction::GenerateIntersection { hit_t }
        }
        RayOp::ConfirmIntersection => RayQueryFunction::ConfirmIntersection,
        RayOp::Terminate => RayQueryFunction::Terminate,
        RayOp::Proceed => {
            // The result is its own expression kind, not an emitted one.
            let result = function
                .expressions
                .append(Expression::RayQueryProceedResult, Span::UNDEFINED);
            body.push(
                Statement::RayQuery {
                    query,
                    fun: RayQueryFunction::Proceed { result },
                },
                Span::UNDEFINED,
            );
            return Ok((result, ctx.intern_scalar(Scalar::BOOL)));
        }
        RayOp::GetCommitted | RayOp::GetCandidate => {
            let ty = ctx.module.generate_ray_intersection_type();
            let handle = emit(
                function,
                body,
                Expression::RayQueryGetIntersection {
                    query,
                    committed: op == RayOp::GetCommitted,
                },
            )?;
            return Ok((handle, ty));
        }
    };

    body.push(Statement::RayQuery { query, fun }, Span::UNDEFINED);
    // Nothing to hand back; the statement path ignores this.
    Ok((query, ctx.intern_scalar(Scalar::U32)))
}
