//! Vector types.
//!
//! Generated by `generate_vector.py`, then `cargo fmt`; edit that, not this.
//!
//! Component access splits two ways: a single `x`/`y`/`z`/`w` is a field, so
//! `v.x` reads and `v.x = 1.0` writes, while every other swizzle is a method.
//! Rust has no way to give one piece of memory a hundred overlapping names, so
//! `v.xyz` has to be `v.xyz()`; `.r`/`.g`/`.b`/`.a` are methods for the same
//! reason, since they would alias the `x`/`y`/`z`/`w` fields.
//!
//! Comparisons are methods too. `a < b` in a shader yields one bool per lane,
//! and Rust's `PartialOrd` yields a single `bool`, so the lane-wise forms are
//! spelled `cmplt`, `cmple`, and so on, as glam spells them.

use core::ops::*;

use crate::unimplemented_on_cpu;

/// The operators every vector has, and the ones only some do.
///
/// `macro_rules!` cannot paste `Add` and `Assign` into one identifier, so each
/// operator names its assigning form too. `$shift` is the `vecNu` a lane-wise
/// shift takes, since WGSL wants an unsigned shift amount whatever is shifted.
macro_rules! vector_ops {
    ($name:ident, $scalar:ty, $shift:ident $(, $group:ident)*) => {
        impl Index<usize> for $name {
            type Output = $scalar;
            #[inline]
            fn index(&self, index: usize) -> &$scalar { unimplemented_on_cpu() }
        }
        impl IndexMut<usize> for $name {
            #[inline]
            fn index_mut(&mut self, index: usize) -> &mut $scalar { unimplemented_on_cpu() }
        }
        $(vector_ops!(@group $group, $name, $scalar, $shift);)*
    };

    (@group arith, $name:ident, $scalar:ty, $shift:ident) => {
        vector_ops!(@scalar_too Add, add, AddAssign, add_assign, $name, $scalar);
        vector_ops!(@scalar_too Sub, sub, SubAssign, sub_assign, $name, $scalar);
        vector_ops!(@scalar_too Mul, mul, MulAssign, mul_assign, $name, $scalar);
        vector_ops!(@scalar_too Div, div, DivAssign, div_assign, $name, $scalar);
        vector_ops!(@scalar_too Rem, rem, RemAssign, rem_assign, $name, $scalar);
    };
    (@group bitwise, $name:ident, $scalar:ty, $shift:ident) => {
        vector_ops!(@lanewise BitAnd, bitand, BitAndAssign, bitand_assign, $name);
        vector_ops!(@lanewise BitOr, bitor, BitOrAssign, bitor_assign, $name);
        vector_ops!(@lanewise BitXor, bitxor, BitXorAssign, bitxor_assign, $name);
    };
    (@group shift, $name:ident, $scalar:ty, $shift:ident) => {
        vector_ops!(@shift Shl, shl, $name, $shift);
        vector_ops!(@shift Shr, shr, $name, $shift);
    };
    (@group neg, $name:ident, $scalar:ty, $shift:ident) => {
        impl Neg for $name {
            type Output = Self;
            #[inline]
            fn neg(self) -> Self { unimplemented_on_cpu() }
        }
    };
    (@group not, $name:ident, $scalar:ty, $shift:ident) => {
        impl Not for $name {
            type Output = Self;
            #[inline]
            fn not(self) -> Self { unimplemented_on_cpu() }
        }
    };

    // Arithmetic also works against a scalar, from either side: a shader
    // writes both `v * 2.0` and `2.0 * v`.
    (@scalar_too $trait:ident, $method:ident, $assign:ident, $assign_fn:ident,
     $name:ident, $scalar:ty) => {
        vector_ops!(@lanewise $trait, $method, $assign, $assign_fn, $name);
        impl $trait<$scalar> for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: $scalar) -> Self { unimplemented_on_cpu() }
        }
        impl $trait<$name> for $scalar {
            type Output = $name;
            #[inline]
            fn $method(self, rhs: $name) -> $name { unimplemented_on_cpu() }
        }
        impl $assign<$scalar> for $name {
            #[inline]
            fn $assign_fn(&mut self, rhs: $scalar) { unimplemented_on_cpu() }
        }
    };
    (@lanewise $trait:ident, $method:ident, $assign:ident, $assign_fn:ident, $name:ident) => {
        impl $trait for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: Self) -> Self { unimplemented_on_cpu() }
        }
        impl $assign for $name {
            #[inline]
            fn $assign_fn(&mut self, rhs: Self) { unimplemented_on_cpu() }
        }
    };
    (@shift $trait:ident, $method:ident, $name:ident, $shift:ident) => {
        impl $trait<$shift> for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: $shift) -> Self { unimplemented_on_cpu() }
        }
        impl $trait<u32> for $name {
            type Output = Self;
            #[inline]
            fn $method(self, rhs: u32) -> Self { unimplemented_on_cpu() }
        }
    };
}

/// `vec2` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec2 {
    pub x: f32,
    pub y: f32,
}

/// Build a [`vec2`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec2(x: f32, y: f32) -> vec2 {
    vec2 { x, y }
}

impl vec2 {
    pub const ZERO: Self = vec2(0.0, 0.0);
    pub const ONE: Self = vec2(1.0, 1.0);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: f32) -> Self {
        vec2(v, v)
    }

    /// One lane wider, with `z` appended. This is how a shader\'s
    /// `vec3(v, z)` is spelled.
    #[inline]
    pub const fn extend(self, z: f32) -> vec3 {
        vec3(self.x, self.y, z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2 {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn yx(self) -> vec2 {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> f32 {
        self.x
    }

    #[inline]
    pub const fn g(self) -> f32 {
        self.y
    }

    #[inline]
    pub const fn rg(self) -> vec2 {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2 {
        vec2(self.y, self.x)
    }
}

vector_ops!(vec2, f32, vec2u, arith, neg);

/// `vec2i` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec2i {
    pub x: i32,
    pub y: i32,
}

/// Build a [`vec2i`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec2i(x: i32, y: i32) -> vec2i {
    vec2i { x, y }
}

impl vec2i {
    pub const ZERO: Self = vec2i(0, 0);
    pub const ONE: Self = vec2i(1, 1);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: i32) -> Self {
        vec2i(v, v)
    }

    /// One lane wider, with `z` appended. This is how a shader\'s
    /// `vec3(v, z)` is spelled.
    #[inline]
    pub const fn extend(self, z: i32) -> vec3i {
        vec3i(self.x, self.y, z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2i {
        vec2i(self.x, self.y)
    }

    #[inline]
    pub const fn yx(self) -> vec2i {
        vec2i(self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> i32 {
        self.x
    }

    #[inline]
    pub const fn g(self) -> i32 {
        self.y
    }

    #[inline]
    pub const fn rg(self) -> vec2i {
        vec2i(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2i {
        vec2i(self.y, self.x)
    }
}

vector_ops!(vec2i, i32, vec2u, arith, bitwise, shift, neg, not);

/// `vec2u` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec2u {
    pub x: u32,
    pub y: u32,
}

/// Build a [`vec2u`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec2u(x: u32, y: u32) -> vec2u {
    vec2u { x, y }
}

impl vec2u {
    pub const ZERO: Self = vec2u(0, 0);
    pub const ONE: Self = vec2u(1, 1);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: u32) -> Self {
        vec2u(v, v)
    }

    /// One lane wider, with `z` appended. This is how a shader\'s
    /// `vec3(v, z)` is spelled.
    #[inline]
    pub const fn extend(self, z: u32) -> vec3u {
        vec3u(self.x, self.y, z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2u {
        vec2u(self.x, self.y)
    }

    #[inline]
    pub const fn yx(self) -> vec2u {
        vec2u(self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> u32 {
        self.x
    }

    #[inline]
    pub const fn g(self) -> u32 {
        self.y
    }

    #[inline]
    pub const fn rg(self) -> vec2u {
        vec2u(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2u {
        vec2u(self.y, self.x)
    }
}

vector_ops!(vec2u, u32, vec2u, arith, bitwise, shift, not);

/// `vec2b` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec2b {
    pub x: bool,
    pub y: bool,
}

/// Build a [`vec2b`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec2b(x: bool, y: bool) -> vec2b {
    vec2b { x, y }
}

impl vec2b {
    pub const ZERO: Self = vec2b(false, false);
    pub const ONE: Self = vec2b(true, true);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: bool) -> Self {
        vec2b(v, v)
    }

    /// One lane wider, with `z` appended. This is how a shader\'s
    /// `vec3(v, z)` is spelled.
    #[inline]
    pub const fn extend(self, z: bool) -> vec3b {
        vec3b(self.x, self.y, z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec2b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2b {
        vec2b(self.x, self.y)
    }

    #[inline]
    pub const fn yx(self) -> vec2b {
        vec2b(self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> bool {
        self.x
    }

    #[inline]
    pub const fn g(self) -> bool {
        self.y
    }

    #[inline]
    pub const fn rg(self) -> vec2b {
        vec2b(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2b {
        vec2b(self.y, self.x)
    }
}

vector_ops!(vec2b, bool, vec2u, bitwise, not);

/// `vec3` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec3 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

/// Build a [`vec3`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec3(x: f32, y: f32, z: f32) -> vec3 {
    vec3 { x, y, z }
}

impl vec3 {
    pub const ZERO: Self = vec3(0.0, 0.0, 0.0);
    pub const ONE: Self = vec3(1.0, 1.0, 1.0);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: f32) -> Self {
        vec3(v, v, v)
    }

    /// One lane wider, with `w` appended. This is how a shader\'s
    /// `vec4(v, w)` is spelled.
    #[inline]
    pub const fn extend(self, w: f32) -> vec4 {
        vec4(self.x, self.y, self.z, w)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> vec2 {
        vec2(self.x, self.y)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2 {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> vec2 {
        vec2(self.x, self.z)
    }

    #[inline]
    pub const fn yx(self) -> vec2 {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> vec2 {
        vec2(self.y, self.z)
    }

    #[inline]
    pub const fn zx(self) -> vec2 {
        vec2(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> vec2 {
        vec2(self.z, self.y)
    }

    #[inline]
    pub const fn xyz(self) -> vec3 {
        vec3(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xzy(self) -> vec3 {
        vec3(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn yxz(self) -> vec3 {
        vec3(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yzx(self) -> vec3 {
        vec3(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn zxy(self) -> vec3 {
        vec3(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zyx(self) -> vec3 {
        vec3(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> f32 {
        self.x
    }

    #[inline]
    pub const fn g(self) -> f32 {
        self.y
    }

    #[inline]
    pub const fn b(self) -> f32 {
        self.z
    }

    #[inline]
    pub const fn rg(self) -> vec2 {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2 {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn rgb(self) -> vec3 {
        vec3(self.x, self.y, self.z)
    }
}

vector_ops!(vec3, f32, vec3u, arith, neg);

/// `vec3i` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec3i {
    pub x: i32,
    pub y: i32,
    pub z: i32,
}

/// Build a [`vec3i`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec3i(x: i32, y: i32, z: i32) -> vec3i {
    vec3i { x, y, z }
}

impl vec3i {
    pub const ZERO: Self = vec3i(0, 0, 0);
    pub const ONE: Self = vec3i(1, 1, 1);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: i32) -> Self {
        vec3i(v, v, v)
    }

    /// One lane wider, with `w` appended. This is how a shader\'s
    /// `vec4(v, w)` is spelled.
    #[inline]
    pub const fn extend(self, w: i32) -> vec4i {
        vec4i(self.x, self.y, self.z, w)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> vec2i {
        vec2i(self.x, self.y)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2i {
        vec2i(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> vec2i {
        vec2i(self.x, self.z)
    }

    #[inline]
    pub const fn yx(self) -> vec2i {
        vec2i(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> vec2i {
        vec2i(self.y, self.z)
    }

    #[inline]
    pub const fn zx(self) -> vec2i {
        vec2i(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> vec2i {
        vec2i(self.z, self.y)
    }

    #[inline]
    pub const fn xyz(self) -> vec3i {
        vec3i(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xzy(self) -> vec3i {
        vec3i(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn yxz(self) -> vec3i {
        vec3i(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yzx(self) -> vec3i {
        vec3i(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn zxy(self) -> vec3i {
        vec3i(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zyx(self) -> vec3i {
        vec3i(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> i32 {
        self.x
    }

    #[inline]
    pub const fn g(self) -> i32 {
        self.y
    }

    #[inline]
    pub const fn b(self) -> i32 {
        self.z
    }

    #[inline]
    pub const fn rg(self) -> vec2i {
        vec2i(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2i {
        vec2i(self.y, self.x)
    }

    #[inline]
    pub const fn rgb(self) -> vec3i {
        vec3i(self.x, self.y, self.z)
    }
}

vector_ops!(vec3i, i32, vec3u, arith, bitwise, shift, neg, not);

/// `vec3u` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec3u {
    pub x: u32,
    pub y: u32,
    pub z: u32,
}

/// Build a [`vec3u`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec3u(x: u32, y: u32, z: u32) -> vec3u {
    vec3u { x, y, z }
}

impl vec3u {
    pub const ZERO: Self = vec3u(0, 0, 0);
    pub const ONE: Self = vec3u(1, 1, 1);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: u32) -> Self {
        vec3u(v, v, v)
    }

    /// One lane wider, with `w` appended. This is how a shader\'s
    /// `vec4(v, w)` is spelled.
    #[inline]
    pub const fn extend(self, w: u32) -> vec4u {
        vec4u(self.x, self.y, self.z, w)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> vec2u {
        vec2u(self.x, self.y)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2u {
        vec2u(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> vec2u {
        vec2u(self.x, self.z)
    }

    #[inline]
    pub const fn yx(self) -> vec2u {
        vec2u(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> vec2u {
        vec2u(self.y, self.z)
    }

    #[inline]
    pub const fn zx(self) -> vec2u {
        vec2u(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> vec2u {
        vec2u(self.z, self.y)
    }

    #[inline]
    pub const fn xyz(self) -> vec3u {
        vec3u(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xzy(self) -> vec3u {
        vec3u(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn yxz(self) -> vec3u {
        vec3u(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yzx(self) -> vec3u {
        vec3u(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn zxy(self) -> vec3u {
        vec3u(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zyx(self) -> vec3u {
        vec3u(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> u32 {
        self.x
    }

    #[inline]
    pub const fn g(self) -> u32 {
        self.y
    }

    #[inline]
    pub const fn b(self) -> u32 {
        self.z
    }

    #[inline]
    pub const fn rg(self) -> vec2u {
        vec2u(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2u {
        vec2u(self.y, self.x)
    }

    #[inline]
    pub const fn rgb(self) -> vec3u {
        vec3u(self.x, self.y, self.z)
    }
}

vector_ops!(vec3u, u32, vec3u, arith, bitwise, shift, not);

/// `vec3b` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec3b {
    pub x: bool,
    pub y: bool,
    pub z: bool,
}

/// Build a [`vec3b`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec3b(x: bool, y: bool, z: bool) -> vec3b {
    vec3b { x, y, z }
}

impl vec3b {
    pub const ZERO: Self = vec3b(false, false, false);
    pub const ONE: Self = vec3b(true, true, true);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: bool) -> Self {
        vec3b(v, v, v)
    }

    /// One lane wider, with `w` appended. This is how a shader\'s
    /// `vec4(v, w)` is spelled.
    #[inline]
    pub const fn extend(self, w: bool) -> vec4b {
        vec4b(self.x, self.y, self.z, w)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> vec2b {
        vec2b(self.x, self.y)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec3b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2b {
        vec2b(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> vec2b {
        vec2b(self.x, self.z)
    }

    #[inline]
    pub const fn yx(self) -> vec2b {
        vec2b(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> vec2b {
        vec2b(self.y, self.z)
    }

    #[inline]
    pub const fn zx(self) -> vec2b {
        vec2b(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> vec2b {
        vec2b(self.z, self.y)
    }

    #[inline]
    pub const fn xyz(self) -> vec3b {
        vec3b(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xzy(self) -> vec3b {
        vec3b(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn yxz(self) -> vec3b {
        vec3b(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yzx(self) -> vec3b {
        vec3b(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn zxy(self) -> vec3b {
        vec3b(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zyx(self) -> vec3b {
        vec3b(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> bool {
        self.x
    }

    #[inline]
    pub const fn g(self) -> bool {
        self.y
    }

    #[inline]
    pub const fn b(self) -> bool {
        self.z
    }

    #[inline]
    pub const fn rg(self) -> vec2b {
        vec2b(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2b {
        vec2b(self.y, self.x)
    }

    #[inline]
    pub const fn rgb(self) -> vec3b {
        vec3b(self.x, self.y, self.z)
    }
}

vector_ops!(vec3b, bool, vec3u, bitwise, not);

/// `vec4` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec4 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}

/// Build a [`vec4`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec4(x: f32, y: f32, z: f32, w: f32) -> vec4 {
    vec4 { x, y, z, w }
}

impl vec4 {
    pub const ZERO: Self = vec4(0.0, 0.0, 0.0, 0.0);
    pub const ONE: Self = vec4(1.0, 1.0, 1.0, 1.0);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: f32) -> Self {
        vec4(v, v, v, v)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> vec3 {
        vec3(self.x, self.y, self.z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2 {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> vec2 {
        vec2(self.x, self.z)
    }

    #[inline]
    pub const fn xw(self) -> vec2 {
        vec2(self.x, self.w)
    }

    #[inline]
    pub const fn yx(self) -> vec2 {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> vec2 {
        vec2(self.y, self.z)
    }

    #[inline]
    pub const fn yw(self) -> vec2 {
        vec2(self.y, self.w)
    }

    #[inline]
    pub const fn zx(self) -> vec2 {
        vec2(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> vec2 {
        vec2(self.z, self.y)
    }

    #[inline]
    pub const fn zw(self) -> vec2 {
        vec2(self.z, self.w)
    }

    #[inline]
    pub const fn wx(self) -> vec2 {
        vec2(self.w, self.x)
    }

    #[inline]
    pub const fn wy(self) -> vec2 {
        vec2(self.w, self.y)
    }

    #[inline]
    pub const fn wz(self) -> vec2 {
        vec2(self.w, self.z)
    }

    #[inline]
    pub const fn xyz(self) -> vec3 {
        vec3(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xyw(self) -> vec3 {
        vec3(self.x, self.y, self.w)
    }

    #[inline]
    pub const fn xzy(self) -> vec3 {
        vec3(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn xzw(self) -> vec3 {
        vec3(self.x, self.z, self.w)
    }

    #[inline]
    pub const fn xwy(self) -> vec3 {
        vec3(self.x, self.w, self.y)
    }

    #[inline]
    pub const fn xwz(self) -> vec3 {
        vec3(self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yxz(self) -> vec3 {
        vec3(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yxw(self) -> vec3 {
        vec3(self.y, self.x, self.w)
    }

    #[inline]
    pub const fn yzx(self) -> vec3 {
        vec3(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn yzw(self) -> vec3 {
        vec3(self.y, self.z, self.w)
    }

    #[inline]
    pub const fn ywx(self) -> vec3 {
        vec3(self.y, self.w, self.x)
    }

    #[inline]
    pub const fn ywz(self) -> vec3 {
        vec3(self.y, self.w, self.z)
    }

    #[inline]
    pub const fn zxy(self) -> vec3 {
        vec3(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zxw(self) -> vec3 {
        vec3(self.z, self.x, self.w)
    }

    #[inline]
    pub const fn zyx(self) -> vec3 {
        vec3(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn zyw(self) -> vec3 {
        vec3(self.z, self.y, self.w)
    }

    #[inline]
    pub const fn zwx(self) -> vec3 {
        vec3(self.z, self.w, self.x)
    }

    #[inline]
    pub const fn zwy(self) -> vec3 {
        vec3(self.z, self.w, self.y)
    }

    #[inline]
    pub const fn wxy(self) -> vec3 {
        vec3(self.w, self.x, self.y)
    }

    #[inline]
    pub const fn wxz(self) -> vec3 {
        vec3(self.w, self.x, self.z)
    }

    #[inline]
    pub const fn wyx(self) -> vec3 {
        vec3(self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wyz(self) -> vec3 {
        vec3(self.w, self.y, self.z)
    }

    #[inline]
    pub const fn wzx(self) -> vec3 {
        vec3(self.w, self.z, self.x)
    }

    #[inline]
    pub const fn wzy(self) -> vec3 {
        vec3(self.w, self.z, self.y)
    }

    #[inline]
    pub const fn xyzw(self) -> vec4 {
        vec4(self.x, self.y, self.z, self.w)
    }

    #[inline]
    pub const fn xywz(self) -> vec4 {
        vec4(self.x, self.y, self.w, self.z)
    }

    #[inline]
    pub const fn xzyw(self) -> vec4 {
        vec4(self.x, self.z, self.y, self.w)
    }

    #[inline]
    pub const fn xzwy(self) -> vec4 {
        vec4(self.x, self.z, self.w, self.y)
    }

    #[inline]
    pub const fn xwyz(self) -> vec4 {
        vec4(self.x, self.w, self.y, self.z)
    }

    #[inline]
    pub const fn xwzy(self) -> vec4 {
        vec4(self.x, self.w, self.z, self.y)
    }

    #[inline]
    pub const fn yxzw(self) -> vec4 {
        vec4(self.y, self.x, self.z, self.w)
    }

    #[inline]
    pub const fn yxwz(self) -> vec4 {
        vec4(self.y, self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yzxw(self) -> vec4 {
        vec4(self.y, self.z, self.x, self.w)
    }

    #[inline]
    pub const fn yzwx(self) -> vec4 {
        vec4(self.y, self.z, self.w, self.x)
    }

    #[inline]
    pub const fn ywxz(self) -> vec4 {
        vec4(self.y, self.w, self.x, self.z)
    }

    #[inline]
    pub const fn ywzx(self) -> vec4 {
        vec4(self.y, self.w, self.z, self.x)
    }

    #[inline]
    pub const fn zxyw(self) -> vec4 {
        vec4(self.z, self.x, self.y, self.w)
    }

    #[inline]
    pub const fn zxwy(self) -> vec4 {
        vec4(self.z, self.x, self.w, self.y)
    }

    #[inline]
    pub const fn zyxw(self) -> vec4 {
        vec4(self.z, self.y, self.x, self.w)
    }

    #[inline]
    pub const fn zywx(self) -> vec4 {
        vec4(self.z, self.y, self.w, self.x)
    }

    #[inline]
    pub const fn zwxy(self) -> vec4 {
        vec4(self.z, self.w, self.x, self.y)
    }

    #[inline]
    pub const fn zwyx(self) -> vec4 {
        vec4(self.z, self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wxyz(self) -> vec4 {
        vec4(self.w, self.x, self.y, self.z)
    }

    #[inline]
    pub const fn wxzy(self) -> vec4 {
        vec4(self.w, self.x, self.z, self.y)
    }

    #[inline]
    pub const fn wyxz(self) -> vec4 {
        vec4(self.w, self.y, self.x, self.z)
    }

    #[inline]
    pub const fn wyzx(self) -> vec4 {
        vec4(self.w, self.y, self.z, self.x)
    }

    #[inline]
    pub const fn wzxy(self) -> vec4 {
        vec4(self.w, self.z, self.x, self.y)
    }

    #[inline]
    pub const fn wzyx(self) -> vec4 {
        vec4(self.w, self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> f32 {
        self.x
    }

    #[inline]
    pub const fn g(self) -> f32 {
        self.y
    }

    #[inline]
    pub const fn b(self) -> f32 {
        self.z
    }

    #[inline]
    pub const fn a(self) -> f32 {
        self.w
    }

    #[inline]
    pub const fn rg(self) -> vec2 {
        vec2(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2 {
        vec2(self.y, self.x)
    }

    #[inline]
    pub const fn ba(self) -> vec2 {
        vec2(self.z, self.w)
    }

    #[inline]
    pub const fn rgb(self) -> vec3 {
        vec3(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn rgba(self) -> vec4 {
        vec4(self.x, self.y, self.z, self.w)
    }
}

vector_ops!(vec4, f32, vec4u, arith, neg);
impl From<(vec2, vec2)> for vec4 {
    #[inline]
    fn from((a, b): (vec2, vec2)) -> Self {
        vec4(a.x, a.y, b.x, b.y)
    }
}

/// `vec4i` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec4i {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub w: i32,
}

/// Build a [`vec4i`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec4i(x: i32, y: i32, z: i32, w: i32) -> vec4i {
    vec4i { x, y, z, w }
}

impl vec4i {
    pub const ZERO: Self = vec4i(0, 0, 0, 0);
    pub const ONE: Self = vec4i(1, 1, 1, 1);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: i32) -> Self {
        vec4i(v, v, v, v)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> vec3i {
        vec3i(self.x, self.y, self.z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2i {
        vec2i(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> vec2i {
        vec2i(self.x, self.z)
    }

    #[inline]
    pub const fn xw(self) -> vec2i {
        vec2i(self.x, self.w)
    }

    #[inline]
    pub const fn yx(self) -> vec2i {
        vec2i(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> vec2i {
        vec2i(self.y, self.z)
    }

    #[inline]
    pub const fn yw(self) -> vec2i {
        vec2i(self.y, self.w)
    }

    #[inline]
    pub const fn zx(self) -> vec2i {
        vec2i(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> vec2i {
        vec2i(self.z, self.y)
    }

    #[inline]
    pub const fn zw(self) -> vec2i {
        vec2i(self.z, self.w)
    }

    #[inline]
    pub const fn wx(self) -> vec2i {
        vec2i(self.w, self.x)
    }

    #[inline]
    pub const fn wy(self) -> vec2i {
        vec2i(self.w, self.y)
    }

    #[inline]
    pub const fn wz(self) -> vec2i {
        vec2i(self.w, self.z)
    }

    #[inline]
    pub const fn xyz(self) -> vec3i {
        vec3i(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xyw(self) -> vec3i {
        vec3i(self.x, self.y, self.w)
    }

    #[inline]
    pub const fn xzy(self) -> vec3i {
        vec3i(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn xzw(self) -> vec3i {
        vec3i(self.x, self.z, self.w)
    }

    #[inline]
    pub const fn xwy(self) -> vec3i {
        vec3i(self.x, self.w, self.y)
    }

    #[inline]
    pub const fn xwz(self) -> vec3i {
        vec3i(self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yxz(self) -> vec3i {
        vec3i(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yxw(self) -> vec3i {
        vec3i(self.y, self.x, self.w)
    }

    #[inline]
    pub const fn yzx(self) -> vec3i {
        vec3i(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn yzw(self) -> vec3i {
        vec3i(self.y, self.z, self.w)
    }

    #[inline]
    pub const fn ywx(self) -> vec3i {
        vec3i(self.y, self.w, self.x)
    }

    #[inline]
    pub const fn ywz(self) -> vec3i {
        vec3i(self.y, self.w, self.z)
    }

    #[inline]
    pub const fn zxy(self) -> vec3i {
        vec3i(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zxw(self) -> vec3i {
        vec3i(self.z, self.x, self.w)
    }

    #[inline]
    pub const fn zyx(self) -> vec3i {
        vec3i(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn zyw(self) -> vec3i {
        vec3i(self.z, self.y, self.w)
    }

    #[inline]
    pub const fn zwx(self) -> vec3i {
        vec3i(self.z, self.w, self.x)
    }

    #[inline]
    pub const fn zwy(self) -> vec3i {
        vec3i(self.z, self.w, self.y)
    }

    #[inline]
    pub const fn wxy(self) -> vec3i {
        vec3i(self.w, self.x, self.y)
    }

    #[inline]
    pub const fn wxz(self) -> vec3i {
        vec3i(self.w, self.x, self.z)
    }

    #[inline]
    pub const fn wyx(self) -> vec3i {
        vec3i(self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wyz(self) -> vec3i {
        vec3i(self.w, self.y, self.z)
    }

    #[inline]
    pub const fn wzx(self) -> vec3i {
        vec3i(self.w, self.z, self.x)
    }

    #[inline]
    pub const fn wzy(self) -> vec3i {
        vec3i(self.w, self.z, self.y)
    }

    #[inline]
    pub const fn xyzw(self) -> vec4i {
        vec4i(self.x, self.y, self.z, self.w)
    }

    #[inline]
    pub const fn xywz(self) -> vec4i {
        vec4i(self.x, self.y, self.w, self.z)
    }

    #[inline]
    pub const fn xzyw(self) -> vec4i {
        vec4i(self.x, self.z, self.y, self.w)
    }

    #[inline]
    pub const fn xzwy(self) -> vec4i {
        vec4i(self.x, self.z, self.w, self.y)
    }

    #[inline]
    pub const fn xwyz(self) -> vec4i {
        vec4i(self.x, self.w, self.y, self.z)
    }

    #[inline]
    pub const fn xwzy(self) -> vec4i {
        vec4i(self.x, self.w, self.z, self.y)
    }

    #[inline]
    pub const fn yxzw(self) -> vec4i {
        vec4i(self.y, self.x, self.z, self.w)
    }

    #[inline]
    pub const fn yxwz(self) -> vec4i {
        vec4i(self.y, self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yzxw(self) -> vec4i {
        vec4i(self.y, self.z, self.x, self.w)
    }

    #[inline]
    pub const fn yzwx(self) -> vec4i {
        vec4i(self.y, self.z, self.w, self.x)
    }

    #[inline]
    pub const fn ywxz(self) -> vec4i {
        vec4i(self.y, self.w, self.x, self.z)
    }

    #[inline]
    pub const fn ywzx(self) -> vec4i {
        vec4i(self.y, self.w, self.z, self.x)
    }

    #[inline]
    pub const fn zxyw(self) -> vec4i {
        vec4i(self.z, self.x, self.y, self.w)
    }

    #[inline]
    pub const fn zxwy(self) -> vec4i {
        vec4i(self.z, self.x, self.w, self.y)
    }

    #[inline]
    pub const fn zyxw(self) -> vec4i {
        vec4i(self.z, self.y, self.x, self.w)
    }

    #[inline]
    pub const fn zywx(self) -> vec4i {
        vec4i(self.z, self.y, self.w, self.x)
    }

    #[inline]
    pub const fn zwxy(self) -> vec4i {
        vec4i(self.z, self.w, self.x, self.y)
    }

    #[inline]
    pub const fn zwyx(self) -> vec4i {
        vec4i(self.z, self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wxyz(self) -> vec4i {
        vec4i(self.w, self.x, self.y, self.z)
    }

    #[inline]
    pub const fn wxzy(self) -> vec4i {
        vec4i(self.w, self.x, self.z, self.y)
    }

    #[inline]
    pub const fn wyxz(self) -> vec4i {
        vec4i(self.w, self.y, self.x, self.z)
    }

    #[inline]
    pub const fn wyzx(self) -> vec4i {
        vec4i(self.w, self.y, self.z, self.x)
    }

    #[inline]
    pub const fn wzxy(self) -> vec4i {
        vec4i(self.w, self.z, self.x, self.y)
    }

    #[inline]
    pub const fn wzyx(self) -> vec4i {
        vec4i(self.w, self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> i32 {
        self.x
    }

    #[inline]
    pub const fn g(self) -> i32 {
        self.y
    }

    #[inline]
    pub const fn b(self) -> i32 {
        self.z
    }

    #[inline]
    pub const fn a(self) -> i32 {
        self.w
    }

    #[inline]
    pub const fn rg(self) -> vec2i {
        vec2i(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2i {
        vec2i(self.y, self.x)
    }

    #[inline]
    pub const fn ba(self) -> vec2i {
        vec2i(self.z, self.w)
    }

    #[inline]
    pub const fn rgb(self) -> vec3i {
        vec3i(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn rgba(self) -> vec4i {
        vec4i(self.x, self.y, self.z, self.w)
    }
}

vector_ops!(vec4i, i32, vec4u, arith, bitwise, shift, neg, not);
impl From<(vec2i, vec2i)> for vec4i {
    #[inline]
    fn from((a, b): (vec2i, vec2i)) -> Self {
        vec4i(a.x, a.y, b.x, b.y)
    }
}

/// `vec4u` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec4u {
    pub x: u32,
    pub y: u32,
    pub z: u32,
    pub w: u32,
}

/// Build a [`vec4u`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec4u(x: u32, y: u32, z: u32, w: u32) -> vec4u {
    vec4u { x, y, z, w }
}

impl vec4u {
    pub const ZERO: Self = vec4u(0, 0, 0, 0);
    pub const ONE: Self = vec4u(1, 1, 1, 1);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: u32) -> Self {
        vec4u(v, v, v, v)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> vec3u {
        vec3u(self.x, self.y, self.z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<`.
    #[inline]
    pub fn cmplt(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `<=`.
    #[inline]
    pub fn cmple(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>`.
    #[inline]
    pub fn cmpgt(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `>=`.
    #[inline]
    pub fn cmpge(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2u {
        vec2u(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> vec2u {
        vec2u(self.x, self.z)
    }

    #[inline]
    pub const fn xw(self) -> vec2u {
        vec2u(self.x, self.w)
    }

    #[inline]
    pub const fn yx(self) -> vec2u {
        vec2u(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> vec2u {
        vec2u(self.y, self.z)
    }

    #[inline]
    pub const fn yw(self) -> vec2u {
        vec2u(self.y, self.w)
    }

    #[inline]
    pub const fn zx(self) -> vec2u {
        vec2u(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> vec2u {
        vec2u(self.z, self.y)
    }

    #[inline]
    pub const fn zw(self) -> vec2u {
        vec2u(self.z, self.w)
    }

    #[inline]
    pub const fn wx(self) -> vec2u {
        vec2u(self.w, self.x)
    }

    #[inline]
    pub const fn wy(self) -> vec2u {
        vec2u(self.w, self.y)
    }

    #[inline]
    pub const fn wz(self) -> vec2u {
        vec2u(self.w, self.z)
    }

    #[inline]
    pub const fn xyz(self) -> vec3u {
        vec3u(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xyw(self) -> vec3u {
        vec3u(self.x, self.y, self.w)
    }

    #[inline]
    pub const fn xzy(self) -> vec3u {
        vec3u(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn xzw(self) -> vec3u {
        vec3u(self.x, self.z, self.w)
    }

    #[inline]
    pub const fn xwy(self) -> vec3u {
        vec3u(self.x, self.w, self.y)
    }

    #[inline]
    pub const fn xwz(self) -> vec3u {
        vec3u(self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yxz(self) -> vec3u {
        vec3u(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yxw(self) -> vec3u {
        vec3u(self.y, self.x, self.w)
    }

    #[inline]
    pub const fn yzx(self) -> vec3u {
        vec3u(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn yzw(self) -> vec3u {
        vec3u(self.y, self.z, self.w)
    }

    #[inline]
    pub const fn ywx(self) -> vec3u {
        vec3u(self.y, self.w, self.x)
    }

    #[inline]
    pub const fn ywz(self) -> vec3u {
        vec3u(self.y, self.w, self.z)
    }

    #[inline]
    pub const fn zxy(self) -> vec3u {
        vec3u(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zxw(self) -> vec3u {
        vec3u(self.z, self.x, self.w)
    }

    #[inline]
    pub const fn zyx(self) -> vec3u {
        vec3u(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn zyw(self) -> vec3u {
        vec3u(self.z, self.y, self.w)
    }

    #[inline]
    pub const fn zwx(self) -> vec3u {
        vec3u(self.z, self.w, self.x)
    }

    #[inline]
    pub const fn zwy(self) -> vec3u {
        vec3u(self.z, self.w, self.y)
    }

    #[inline]
    pub const fn wxy(self) -> vec3u {
        vec3u(self.w, self.x, self.y)
    }

    #[inline]
    pub const fn wxz(self) -> vec3u {
        vec3u(self.w, self.x, self.z)
    }

    #[inline]
    pub const fn wyx(self) -> vec3u {
        vec3u(self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wyz(self) -> vec3u {
        vec3u(self.w, self.y, self.z)
    }

    #[inline]
    pub const fn wzx(self) -> vec3u {
        vec3u(self.w, self.z, self.x)
    }

    #[inline]
    pub const fn wzy(self) -> vec3u {
        vec3u(self.w, self.z, self.y)
    }

    #[inline]
    pub const fn xyzw(self) -> vec4u {
        vec4u(self.x, self.y, self.z, self.w)
    }

    #[inline]
    pub const fn xywz(self) -> vec4u {
        vec4u(self.x, self.y, self.w, self.z)
    }

    #[inline]
    pub const fn xzyw(self) -> vec4u {
        vec4u(self.x, self.z, self.y, self.w)
    }

    #[inline]
    pub const fn xzwy(self) -> vec4u {
        vec4u(self.x, self.z, self.w, self.y)
    }

    #[inline]
    pub const fn xwyz(self) -> vec4u {
        vec4u(self.x, self.w, self.y, self.z)
    }

    #[inline]
    pub const fn xwzy(self) -> vec4u {
        vec4u(self.x, self.w, self.z, self.y)
    }

    #[inline]
    pub const fn yxzw(self) -> vec4u {
        vec4u(self.y, self.x, self.z, self.w)
    }

    #[inline]
    pub const fn yxwz(self) -> vec4u {
        vec4u(self.y, self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yzxw(self) -> vec4u {
        vec4u(self.y, self.z, self.x, self.w)
    }

    #[inline]
    pub const fn yzwx(self) -> vec4u {
        vec4u(self.y, self.z, self.w, self.x)
    }

    #[inline]
    pub const fn ywxz(self) -> vec4u {
        vec4u(self.y, self.w, self.x, self.z)
    }

    #[inline]
    pub const fn ywzx(self) -> vec4u {
        vec4u(self.y, self.w, self.z, self.x)
    }

    #[inline]
    pub const fn zxyw(self) -> vec4u {
        vec4u(self.z, self.x, self.y, self.w)
    }

    #[inline]
    pub const fn zxwy(self) -> vec4u {
        vec4u(self.z, self.x, self.w, self.y)
    }

    #[inline]
    pub const fn zyxw(self) -> vec4u {
        vec4u(self.z, self.y, self.x, self.w)
    }

    #[inline]
    pub const fn zywx(self) -> vec4u {
        vec4u(self.z, self.y, self.w, self.x)
    }

    #[inline]
    pub const fn zwxy(self) -> vec4u {
        vec4u(self.z, self.w, self.x, self.y)
    }

    #[inline]
    pub const fn zwyx(self) -> vec4u {
        vec4u(self.z, self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wxyz(self) -> vec4u {
        vec4u(self.w, self.x, self.y, self.z)
    }

    #[inline]
    pub const fn wxzy(self) -> vec4u {
        vec4u(self.w, self.x, self.z, self.y)
    }

    #[inline]
    pub const fn wyxz(self) -> vec4u {
        vec4u(self.w, self.y, self.x, self.z)
    }

    #[inline]
    pub const fn wyzx(self) -> vec4u {
        vec4u(self.w, self.y, self.z, self.x)
    }

    #[inline]
    pub const fn wzxy(self) -> vec4u {
        vec4u(self.w, self.z, self.x, self.y)
    }

    #[inline]
    pub const fn wzyx(self) -> vec4u {
        vec4u(self.w, self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> u32 {
        self.x
    }

    #[inline]
    pub const fn g(self) -> u32 {
        self.y
    }

    #[inline]
    pub const fn b(self) -> u32 {
        self.z
    }

    #[inline]
    pub const fn a(self) -> u32 {
        self.w
    }

    #[inline]
    pub const fn rg(self) -> vec2u {
        vec2u(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2u {
        vec2u(self.y, self.x)
    }

    #[inline]
    pub const fn ba(self) -> vec2u {
        vec2u(self.z, self.w)
    }

    #[inline]
    pub const fn rgb(self) -> vec3u {
        vec3u(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn rgba(self) -> vec4u {
        vec4u(self.x, self.y, self.z, self.w)
    }
}

vector_ops!(vec4u, u32, vec4u, arith, bitwise, shift, not);
impl From<(vec2u, vec2u)> for vec4u {
    #[inline]
    fn from((a, b): (vec2u, vec2u)) -> Self {
        vec4u(a.x, a.y, b.x, b.y)
    }
}

/// `vec4b` in WGSL.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
#[allow(non_camel_case_types)]
pub struct vec4b {
    pub x: bool,
    pub y: bool,
    pub z: bool,
    pub w: bool,
}

/// Build a [`vec4b`] from its components.
#[allow(non_snake_case)]
#[inline]
pub const fn vec4b(x: bool, y: bool, z: bool, w: bool) -> vec4b {
    vec4b { x, y, z, w }
}

impl vec4b {
    pub const ZERO: Self = vec4b(false, false, false, false);
    pub const ONE: Self = vec4b(true, true, true, true);

    /// Every lane set to `v`.
    #[inline]
    pub const fn splat(v: bool) -> Self {
        vec4b(v, v, v, v)
    }

    /// One lane narrower, dropping the last.
    #[inline]
    pub const fn truncate(self) -> vec3b {
        vec3b(self.x, self.y, self.z)
    }

    /// Lane-wise `==`.
    #[inline]
    pub fn cmpeq(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    /// Lane-wise `!=`.
    #[inline]
    pub fn cmpne(self, rhs: Self) -> vec4b {
        unimplemented_on_cpu()
    }

    #[inline]
    pub const fn xy(self) -> vec2b {
        vec2b(self.x, self.y)
    }

    #[inline]
    pub const fn xz(self) -> vec2b {
        vec2b(self.x, self.z)
    }

    #[inline]
    pub const fn xw(self) -> vec2b {
        vec2b(self.x, self.w)
    }

    #[inline]
    pub const fn yx(self) -> vec2b {
        vec2b(self.y, self.x)
    }

    #[inline]
    pub const fn yz(self) -> vec2b {
        vec2b(self.y, self.z)
    }

    #[inline]
    pub const fn yw(self) -> vec2b {
        vec2b(self.y, self.w)
    }

    #[inline]
    pub const fn zx(self) -> vec2b {
        vec2b(self.z, self.x)
    }

    #[inline]
    pub const fn zy(self) -> vec2b {
        vec2b(self.z, self.y)
    }

    #[inline]
    pub const fn zw(self) -> vec2b {
        vec2b(self.z, self.w)
    }

    #[inline]
    pub const fn wx(self) -> vec2b {
        vec2b(self.w, self.x)
    }

    #[inline]
    pub const fn wy(self) -> vec2b {
        vec2b(self.w, self.y)
    }

    #[inline]
    pub const fn wz(self) -> vec2b {
        vec2b(self.w, self.z)
    }

    #[inline]
    pub const fn xyz(self) -> vec3b {
        vec3b(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn xyw(self) -> vec3b {
        vec3b(self.x, self.y, self.w)
    }

    #[inline]
    pub const fn xzy(self) -> vec3b {
        vec3b(self.x, self.z, self.y)
    }

    #[inline]
    pub const fn xzw(self) -> vec3b {
        vec3b(self.x, self.z, self.w)
    }

    #[inline]
    pub const fn xwy(self) -> vec3b {
        vec3b(self.x, self.w, self.y)
    }

    #[inline]
    pub const fn xwz(self) -> vec3b {
        vec3b(self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yxz(self) -> vec3b {
        vec3b(self.y, self.x, self.z)
    }

    #[inline]
    pub const fn yxw(self) -> vec3b {
        vec3b(self.y, self.x, self.w)
    }

    #[inline]
    pub const fn yzx(self) -> vec3b {
        vec3b(self.y, self.z, self.x)
    }

    #[inline]
    pub const fn yzw(self) -> vec3b {
        vec3b(self.y, self.z, self.w)
    }

    #[inline]
    pub const fn ywx(self) -> vec3b {
        vec3b(self.y, self.w, self.x)
    }

    #[inline]
    pub const fn ywz(self) -> vec3b {
        vec3b(self.y, self.w, self.z)
    }

    #[inline]
    pub const fn zxy(self) -> vec3b {
        vec3b(self.z, self.x, self.y)
    }

    #[inline]
    pub const fn zxw(self) -> vec3b {
        vec3b(self.z, self.x, self.w)
    }

    #[inline]
    pub const fn zyx(self) -> vec3b {
        vec3b(self.z, self.y, self.x)
    }

    #[inline]
    pub const fn zyw(self) -> vec3b {
        vec3b(self.z, self.y, self.w)
    }

    #[inline]
    pub const fn zwx(self) -> vec3b {
        vec3b(self.z, self.w, self.x)
    }

    #[inline]
    pub const fn zwy(self) -> vec3b {
        vec3b(self.z, self.w, self.y)
    }

    #[inline]
    pub const fn wxy(self) -> vec3b {
        vec3b(self.w, self.x, self.y)
    }

    #[inline]
    pub const fn wxz(self) -> vec3b {
        vec3b(self.w, self.x, self.z)
    }

    #[inline]
    pub const fn wyx(self) -> vec3b {
        vec3b(self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wyz(self) -> vec3b {
        vec3b(self.w, self.y, self.z)
    }

    #[inline]
    pub const fn wzx(self) -> vec3b {
        vec3b(self.w, self.z, self.x)
    }

    #[inline]
    pub const fn wzy(self) -> vec3b {
        vec3b(self.w, self.z, self.y)
    }

    #[inline]
    pub const fn xyzw(self) -> vec4b {
        vec4b(self.x, self.y, self.z, self.w)
    }

    #[inline]
    pub const fn xywz(self) -> vec4b {
        vec4b(self.x, self.y, self.w, self.z)
    }

    #[inline]
    pub const fn xzyw(self) -> vec4b {
        vec4b(self.x, self.z, self.y, self.w)
    }

    #[inline]
    pub const fn xzwy(self) -> vec4b {
        vec4b(self.x, self.z, self.w, self.y)
    }

    #[inline]
    pub const fn xwyz(self) -> vec4b {
        vec4b(self.x, self.w, self.y, self.z)
    }

    #[inline]
    pub const fn xwzy(self) -> vec4b {
        vec4b(self.x, self.w, self.z, self.y)
    }

    #[inline]
    pub const fn yxzw(self) -> vec4b {
        vec4b(self.y, self.x, self.z, self.w)
    }

    #[inline]
    pub const fn yxwz(self) -> vec4b {
        vec4b(self.y, self.x, self.w, self.z)
    }

    #[inline]
    pub const fn yzxw(self) -> vec4b {
        vec4b(self.y, self.z, self.x, self.w)
    }

    #[inline]
    pub const fn yzwx(self) -> vec4b {
        vec4b(self.y, self.z, self.w, self.x)
    }

    #[inline]
    pub const fn ywxz(self) -> vec4b {
        vec4b(self.y, self.w, self.x, self.z)
    }

    #[inline]
    pub const fn ywzx(self) -> vec4b {
        vec4b(self.y, self.w, self.z, self.x)
    }

    #[inline]
    pub const fn zxyw(self) -> vec4b {
        vec4b(self.z, self.x, self.y, self.w)
    }

    #[inline]
    pub const fn zxwy(self) -> vec4b {
        vec4b(self.z, self.x, self.w, self.y)
    }

    #[inline]
    pub const fn zyxw(self) -> vec4b {
        vec4b(self.z, self.y, self.x, self.w)
    }

    #[inline]
    pub const fn zywx(self) -> vec4b {
        vec4b(self.z, self.y, self.w, self.x)
    }

    #[inline]
    pub const fn zwxy(self) -> vec4b {
        vec4b(self.z, self.w, self.x, self.y)
    }

    #[inline]
    pub const fn zwyx(self) -> vec4b {
        vec4b(self.z, self.w, self.y, self.x)
    }

    #[inline]
    pub const fn wxyz(self) -> vec4b {
        vec4b(self.w, self.x, self.y, self.z)
    }

    #[inline]
    pub const fn wxzy(self) -> vec4b {
        vec4b(self.w, self.x, self.z, self.y)
    }

    #[inline]
    pub const fn wyxz(self) -> vec4b {
        vec4b(self.w, self.y, self.x, self.z)
    }

    #[inline]
    pub const fn wyzx(self) -> vec4b {
        vec4b(self.w, self.y, self.z, self.x)
    }

    #[inline]
    pub const fn wzxy(self) -> vec4b {
        vec4b(self.w, self.z, self.x, self.y)
    }

    #[inline]
    pub const fn wzyx(self) -> vec4b {
        vec4b(self.w, self.z, self.y, self.x)
    }

    #[inline]
    pub const fn r(self) -> bool {
        self.x
    }

    #[inline]
    pub const fn g(self) -> bool {
        self.y
    }

    #[inline]
    pub const fn b(self) -> bool {
        self.z
    }

    #[inline]
    pub const fn a(self) -> bool {
        self.w
    }

    #[inline]
    pub const fn rg(self) -> vec2b {
        vec2b(self.x, self.y)
    }

    #[inline]
    pub const fn gr(self) -> vec2b {
        vec2b(self.y, self.x)
    }

    #[inline]
    pub const fn ba(self) -> vec2b {
        vec2b(self.z, self.w)
    }

    #[inline]
    pub const fn rgb(self) -> vec3b {
        vec3b(self.x, self.y, self.z)
    }

    #[inline]
    pub const fn rgba(self) -> vec4b {
        vec4b(self.x, self.y, self.z, self.w)
    }
}

vector_ops!(vec4b, bool, vec4u, bitwise, not);
impl From<(vec2b, vec2b)> for vec4b {
    #[inline]
    fn from((a, b): (vec2b, vec2b)) -> Self {
        vec4b(a.x, a.y, b.x, b.y)
    }
}

impl From<vec2> for vec2i {
    #[inline]
    fn from(v: vec2) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2> for vec2u {
    #[inline]
    fn from(v: vec2) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2> for vec2b {
    #[inline]
    fn from(v: vec2) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2i> for vec2 {
    #[inline]
    fn from(v: vec2i) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2i> for vec2u {
    #[inline]
    fn from(v: vec2i) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2i> for vec2b {
    #[inline]
    fn from(v: vec2i) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2u> for vec2 {
    #[inline]
    fn from(v: vec2u) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2u> for vec2i {
    #[inline]
    fn from(v: vec2u) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2u> for vec2b {
    #[inline]
    fn from(v: vec2u) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2b> for vec2 {
    #[inline]
    fn from(v: vec2b) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2b> for vec2i {
    #[inline]
    fn from(v: vec2b) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec2b> for vec2u {
    #[inline]
    fn from(v: vec2b) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3> for vec3i {
    #[inline]
    fn from(v: vec3) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3> for vec3u {
    #[inline]
    fn from(v: vec3) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3> for vec3b {
    #[inline]
    fn from(v: vec3) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3i> for vec3 {
    #[inline]
    fn from(v: vec3i) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3i> for vec3u {
    #[inline]
    fn from(v: vec3i) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3i> for vec3b {
    #[inline]
    fn from(v: vec3i) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3u> for vec3 {
    #[inline]
    fn from(v: vec3u) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3u> for vec3i {
    #[inline]
    fn from(v: vec3u) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3u> for vec3b {
    #[inline]
    fn from(v: vec3u) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3b> for vec3 {
    #[inline]
    fn from(v: vec3b) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3b> for vec3i {
    #[inline]
    fn from(v: vec3b) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec3b> for vec3u {
    #[inline]
    fn from(v: vec3b) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4> for vec4i {
    #[inline]
    fn from(v: vec4) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4> for vec4u {
    #[inline]
    fn from(v: vec4) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4> for vec4b {
    #[inline]
    fn from(v: vec4) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4i> for vec4 {
    #[inline]
    fn from(v: vec4i) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4i> for vec4u {
    #[inline]
    fn from(v: vec4i) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4i> for vec4b {
    #[inline]
    fn from(v: vec4i) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4u> for vec4 {
    #[inline]
    fn from(v: vec4u) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4u> for vec4i {
    #[inline]
    fn from(v: vec4u) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4u> for vec4b {
    #[inline]
    fn from(v: vec4u) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4b> for vec4 {
    #[inline]
    fn from(v: vec4b) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4b> for vec4i {
    #[inline]
    fn from(v: vec4b) -> Self {
        unimplemented_on_cpu()
    }
}
impl From<vec4b> for vec4u {
    #[inline]
    fn from(v: vec4b) -> Self {
        unimplemented_on_cpu()
    }
}
